version: '3'

services:
  varnish:
    image: varnish:stable
    volumes:
      - ./main.vcl:/etc/varnish/default.vcl
    ports:
      - "8080:80"
    depends_on:
      - backend-a
      - backend-b

  backend-a:
    image: nginx:alpine
    volumes:
      - ./backend-a/index.html:/usr/share/nginx/html/index.html
    expose:
      - "80"

  backend-b:
    image: nginx:alpine
    volumes:
      - ./backend-b/index.html:/usr/share/nginx/html/index.html
    expose:
      - "80"